version: "2.0"

networks:
  # Specify the network for bridging
  zkspv__services_network:
    driver: bridge
    external: true

services:
  circuit:
    build:
      context: ./
      dockerfile: cuda_12.2_amd64.Dockerfile
    command: ./target/release/services --cache_srs_pk --generate_smart_contract
    restart: always
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   # - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    #   - ENABLE_CUDA=1
    networks:
      - zkspv__services_network
    ports:
      - "80:3030"
    volumes:
      - ./data:/usr/src/zkSpv/data
      - ./cache_data:/usr/src/zkSpv/cache_data
      - ./params:/usr/src/zkSpv/params
      - ./challenges_db:/usr/src/zkSpv/challenges_db
      - ./log:/usr/src/zkSpv/log
      - ./spv.toml:/usr/src/zkSpv/spv.toml
    # devices:
    #   - /dev/nvidia0:/dev/nvidia0
      # - /dev/nvidiactl:/dev/nvidiactl
      # - /dev/nvidia-caps:/dev/nvidia-caps
      # - /dev/nvidia-modeset:/dev/nvidia-modeset
      # - /dev/nvidia-uvm:/dev/nvidia-uvm
      # - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      # - driver: "nvidia"
      #   count: "all"
      #   capabilities: ["gpu"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: all
    #         capabilities: [gpu]