version: "2.0"

networks:
  # Specify the network for bridging
  zkspv__services_network:
    driver: bridge
    external: true

services:
  circuit:
    build:
      context: ./
#      dockerfile: 20.04_amd64_cuda_12_0.Dockerfile
      dockerfile: cuda_12.2_amd64.Dockerfile
    command: ./target/release/arbitration_business
    # command: sleep 3000
    restart: always
    networks:
      - zkspv__services_network
    volumes:
      - .data/cache_data:/cache_data
      - .data/setup:/params
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools